<?php

/**
 * @file
 * Contains ckeditor_plugins.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_plugins_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.ckeditor_plugins':
      $output = '';
      $output .= '<h3>' . t('Ckeditor Plugins') . '</h3>';
      $output .= '<p>' . t('The module adds custom buttons to the editor toolbar.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Settings') . '</dt>';
      $output .= '<dd>' . t('In the <a href=":text-formats">text formats</a> that use ckeditor, move the custom icons into the active toolbar.', [':text-formats' => \Drupal::url('filter.admin_overview')]) . '</dd>';
      $output .= '</dl>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function ckeditor_plugins_page_attachments_alter(array &$page)
{
  // Attaches css assets globally.
  $page['#attached']['library'][] = 'ckeditor_plugins/ckeditor_plugins_style';
}
